### ISSUE TITLE
Extra item for Translation

### ISSUE THREAD

**Issue by anaisbetts** [kitze/voice-command-list#7]
You can also say "WORD in German/Spanish/whatever" and it will translate it. 

Pro-Tip, if you go into settings and enable secondary languages, it means that you can translate two-way between them. So, I enable German as my secondary search language, then say "SOME_WORD auf Englisch"  or "SOME_WORD in German" then don't have to open Google Translate

**Comment by anaisbetts** [comment]
Also, great project! I'll be looking at this quite a bit

**Comment by kitze** [comment]
Thanks, i will add this one! 👍
